#!/bin/bash

# Call the screenshotter with all args
LINK=$(evgeny_screenshot $@ --date --upload ubuntu@epochfail.com --key ~/.ssh/archimedes www_root/f)
LINK=${LINK/archimedes./}

notify-send $LINK
echo $LINK
echo $LINK | copy
